### ISSUE TITLE
给力。

### ISSUE THREAD

**Issue by iamxz** [grasses/NetEase-Wireless-MusicBox#2]
给力~~~

**Comment by grasses** [comment]
树莓派就是接收端+播放端，手机（web）是控制端。

**Comment by iamxz** [comment]
我想说的是 手机请求各个接口数据 然后把播放的信号 传给 树莓派。举个例子，手机上打开一个qq播放器，通过 dlna 之类的 传给树莓派 。

**Comment by grasses** [comment]
我查查资料，看看还能改进出什么。谢谢啦。
